/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Y8Jlck6IDAX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function GitRepoAnalyzer() {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    try {
      await new Promise((resolve) => setTimeout(resolve, 3000))
      setLoading(false)
      setError(null)
    } catch (err) {
      setLoading(false)
      setError("Error loading repository")
    }
  }
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-muted p-4">
        <nav className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-lg font-bold" prefetch={false}>
            Git Repo Viewer
          </Link>
          <div className="flex items-center space-x-4">
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Search
            </Link>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Favorites
            </Link>
          </div>
        </nav>
      </header>
      <main className="flex-1 py-12">
        <Card className="mx-auto max-w-md p-6 bg-background border">
          <CardHeader>
            <CardTitle className="text-2xl font-bold">Git Repo Viewer</CardTitle>
            <CardDescription className="text-muted-foreground">
              Enter a repository URL and branch to view.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <form onSubmit={handleSubmit}>
              <div className="space-y-2">
                <Label htmlFor="repo-url">Repository URL</Label>
                <Input id="repo-url" placeholder="https://github.com/user/repo.git" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="branch-name">Branch Name</Label>
                <Input id="branch-name" placeholder="main" required />
              </div>
              {loading ? (
                <div className="flex flex-col items-center justify-center py-8 space-y-4">
                  <div className="h-8 w-8 animate-spin" />
                  <div className="text-muted-foreground">Loading...</div>
                  <div className="text-sm text-muted-foreground">This may take a few seconds...</div>
                </div>
              ) : (
                <Button type="submit" className="w-full">
                  View Repository
                </Button>
              )}
              {error && <div className="mt-4 rounded-md bg-red-500/10 p-4 text-red-500">{error}</div>}
            </form>
          </CardContent>
        </Card>
      </main>
      <footer className="bg-muted p-4 text-center text-muted-foreground">
        <div className="container mx-auto">&copy; 2024 Git Repo Viewer. All rights reserved.</div>
      </footer>
    </div>
  )
}
